-- Enable Row Level Security on all tables
ALTER TABLE families ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE family_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE family_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE template_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_template_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE template_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE line_item_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_itineraries ENABLE ROW LEVEL SECURITY;
ALTER TABLE itinerary_template_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE planning_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE planning_session_items ENABLE ROW LEVEL SECURITY;